# Generated by Django 6.0.7 on 2026-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
